name: CI - Deno + Fresh + PostgreSQL

on:
  push:
    branches: ["main", "dev"]
  pull_request:
    branches: ["main"]

jobs:
  test:
    name: Check and Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5.0.0

      - name: Set up Deno
        uses: denoland/setup-deno@v2.0.3
        with:
          deno-version: v2.x

      - name: Cache Deno modules
        uses: actions/cache@v4.3.0
        with:
          path: ~/.cache/deno
          key: ${{ runner.os }}-deno-${{ hashFiles('deno.lock') }}
          restore-keys: |
            ${{ runner.os }}-deno-

      - name: Install dependencies (deno cache)
        run: deno cache ./main.ts

      - name: Check formatting
        run: deno fmt --check

      - name: Lint
        run: deno lint

      - name: Type check (deno check)
        run: deno check

      - name: Run tests
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
        run: deno test --allow-net --allow-env --allow-read
